run_table: "samples.txt"

directories:
  nobackup_fastq: "/users/mirimia/liniguez/no_backup/liniguez/fastqs"
  references: "/users/mirimia/liniguez/references/"

translateSP:
  Cel: "cel"

genome:
  Cel: "http://ftp.ensembl.org/pub/release-104/fasta/caenorhabditis_elegans/dna/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz"

annotation:
  Cel: "/users/mirimia/liniguez/references/MiniManuTest/test.gtf"
